# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
version: 2.1
orbs:
  jira: circleci/jira@2.1.0
jobs:
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - jira/notify:
          webhook_url: https://128227a1-b1f0-4c2b-b7b6-1b32a1afee83.hello.atlassian-dev.net/x1/vBJnjZKCf90-Lpe-jwiC-23hmJc
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
workflows:
  example:
    jobs:
      - build:
          context: JIRA_WEBHOOK
      - deploy:
          context: JIRA_WEBHOOK